---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: simple-server
    colour: vlue
  name: simple-server
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30255
  selector:
    app: simple-server
  type: NodePort
status:
  loadBalancer: {}