apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simple-server
  name: simple-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-server
      colour: green
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple-server
        colour: green
    spec:
      containers:
      - image: wrightda/simpleserver:0.1.0
        name: simpleserver
        args:
        - green  
        resources: {}
status: {}
